version: '3.8'
services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - JWT_SECRET=naotivenadaemmenteparapensar
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
