version: '3.8'
services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - JWT_SECRET=alterar-isso-em-prod
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./node_modules:/usr/src/app/node_modules
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
